# Site settings
title: "Minds and Machines"
description: "A podcast about AI and large language models"
podcast-description: "A podcast about AI and large language models"
url:  "https://podcast.johndorion.com/" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Sheyanne Barr, Elysia Carson, Charlie Do, John Dorion, Brandon Guerrero, Jonathan Hampton, Walter Horton, Meenakshi Malkar, Alisha Mccoy, Lillian Pierce, Mary Sharp, Ebony Wells"
  email: "john@johndorion.com"
  url: "https://podcast.johndorion.com"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username:
  card:
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Minds and Machines
  links:
    - https://twitter.com/
    - https://www.linkedin.com/
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Minds and Machines
podcast_author: Sheyanne Barr, Elysia Carson, Charlie Do, John Dorion, Brandon Guerrero, Jonathan Hampton, Walter Horton, Meenakshi Malkar, Alisha Mccoy, Lillian Pierce, Mary Sharp, Ebony Wells
podcast_email: john@johndorion.com
podcast_subtitle: "A podcast about AI and large language models"
podcast_summary: "A podcast about AI and large language models"
podcast_description: "A podcast about AI and large language models"
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2023-06-23" #Launch date of your podcast
podcast_copyright: "&#xA9;Minds and Machines"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
